services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:3000
    depends_on:
      - backend
    user: "prod"
    networks:
      - mynet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/agent
    command: bash -c "python3 /agent/launch.py"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge